### ISSUE TITLE
Spam in client chat

### ISSUE THREAD

**Issue by Xen1290** [Lithial/More-Enchantments-1.7.10#1]
Hi @Lithial , with latest version there is a spam issue,when you hurt an entity like this:
player did 1 damage
player did 1 damage

I think the problem is here, you forgot to disable this:
https://github.com/Lithial/More-Enchantments-1.7.10/blob/master/src/main/java/com/lithial/me/handlers/DamageHandler.java#L142
Sorry for bad english.

**Comment by Lithial** [comment]
Yea I fixed it last night but I fell asleep before I could release it. I'll push my changes tonight and do a release. I should also be able to set up my auto release system soon because this is my last day of work for 3 days

**Comment by Xen1290** [comment]
Perfect, thanks for your hard work! Keep it up!

**Comment by Xen1290** [comment]
Spam fixed with latest version, closing.
Thanks!
